blank_issues_enabled: false
contact_links:
  - name: Request Support
    url: https://forum.freecodecamp.org
    about: Visit our community forum for support and FAQs
  - name: Request technical support for your freeCodeCamp account
    url: https://www.freecodecamp.org/support
    about: Please visit this page for requesting technical support related to your freeCodeCamp account.
